#!/usr/bin/env python3
"""Diff the working manuscript against the frozen Novelcrafter export.

The export under source/raw/<date>-novelcrafter-export/novel.md is the last
import baseline. This finds where the working text (chapters/ via the
compiled source/book*.txt) has since diverged, so the divergence is known
if a fresh export is ever re-imported.

Normalisation strips the cosmetic differences (the export's ``* * *`` scene
breaks vs the working text's scene-title lines, smart quotes, dashes,
whitespace) so only real prose changes remain. Output is a per-chapter
report: changed/added/removed paragraphs, plus chapters that exist only in
the working copy (e.g. material written after the export).

Zero third-party dependencies. Python 3.8+.
"""
from __future__ import annotations

import argparse
import difflib
import glob
import re
import sys

EXPORT_DEFAULT = "source/raw/2026-06-23-novelcrafter-export/novel.md"


def _norm(p):
    """Normalise a paragraph so cosmetic differences don't read as edits."""
    p = p.replace("’", "'").replace("‘", "'")
    p = p.replace("“", '"').replace("”", '"')
    p = p.replace("—", "-").replace("–", "-").replace("…", "...")
    p = re.sub(r"\s+", " ", p).strip()
    return p


def export_chapters(path):
    """Return ({chapter: [paras]}, {part titles}) from the export markdown.

    Part/arc dividers ('## Emotional Stakes') are captured separately so the
    same titles can be stripped from the working text, where they appear as
    plain lines rather than headers.
    """
    chaps, cur, buf = {}, None, []
    parts = set()
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            m = re.match(r"^###\s+Chapter\s+(\d+)\s*:", line)
            if m:
                if cur is not None:
                    chaps[cur] = buf
                cur, buf = int(m.group(1)), []
                continue
            if re.match(r"^##\s+\S", line):          # part/arc divider
                parts.add(_norm(line.lstrip("# ").strip()))
                continue
            if line.startswith("#"):
                continue
            s = line.strip()
            if not s or set(s) <= {"*", " "}:   # blank or '* * *' scene break
                continue
            if cur is not None:
                buf.append(_norm(s))
    if cur is not None:
        chaps[cur] = buf
    return chaps, parts


def work_chapters(paths, parts=frozenset()):
    """{chapter_number: [normalised paragraphs]} from the working book files.

    Drops 'Scene N' markers *and* the scene-title line that follows them, plus
    any line matching an export part title, so structural lines don't show up
    as prose changes against the export.
    """
    chaps, cur, buf, expect_title = {}, None, [], False
    for path in paths:
        if cur is not None:        # don't let one book's title bleed into the
            chaps[cur] = buf       # previous book's final chapter
            cur, buf, expect_title = None, [], False
        for line in open(path, encoding="utf-8"):
            s = line.strip()
            m = re.match(r"^Chapter\s+(\d+)\s*:", s)
            if m:
                if cur is not None:
                    chaps[cur] = buf
                cur, buf, expect_title = int(m.group(1)), [], False
                continue
            if re.match(r"^Scene\s+\d+", s, re.I):
                expect_title = True       # the next non-empty line is a title
                continue
            if not s:
                continue
            if expect_title:
                expect_title = False      # consume the scene-title line
                continue
            if _norm(s) in parts:         # a part/arc divider line
                continue
            if cur is not None:
                buf.append(_norm(s))
    if cur is not None:
        chaps[cur] = buf
    return chaps


def diff_chapter(exp, wrk):
    """Return list of (tag, [export paras], [work paras]) for changed blocks."""
    sm = difflib.SequenceMatcher(None, exp, wrk, autojunk=False)
    blocks = []
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag != "equal":
            blocks.append((tag, exp[i1:i2], wrk[j1:j2]))
    return blocks


def render(exp, wrk, context):
    out = ["# Divergence from the Novelcrafter export (auto-generated)", ""]
    out.append("Baseline: the frozen export; working text: `source/book*.txt`. "
               "Cosmetic differences (scene-break style, quotes, dashes) are "
               "normalised away. Generated by `tools/diff_export.py`.")
    out.append("")
    only_work = sorted(set(wrk) - set(exp))
    only_exp = sorted(set(exp) - set(wrk))
    out.append(f"Chapters in export: {min(exp)}–{max(exp)} ({len(exp)}). "
               f"Working: {min(wrk)}–{max(wrk)} ({len(wrk)}).")
    if only_work:
        out.append(f"- **Only in working copy (written after export):** "
                   f"{', '.join('ch'+str(c) for c in only_work)}")
    if only_exp:
        out.append(f"- **Only in export (removed from working):** "
                   f"{', '.join('ch'+str(c) for c in only_exp)}")
    out.append("")

    total_changed = 0
    for ch in sorted(set(exp) & set(wrk)):
        blocks = diff_chapter(exp[ch], wrk[ch])
        if not blocks:
            continue
        total_changed += 1
        nchg = sum(len(b[1]) + len(b[2]) for b in blocks)
        out.append(f"## Chapter {ch} — {len(blocks)} changed block(s)")
        out.append("")
        for tag, ex, wk in blocks:
            label = {"replace": "changed", "delete": "removed",
                     "insert": "added"}[tag]
            out.append(f"### {label}")
            for p in ex:
                out.append(f"- − {p[:context]}" + ("…" if len(p) > context else ""))
            for p in wk:
                out.append(f"- ＋ {p[:context]}" + ("…" if len(p) > context else ""))
            out.append("")
    head = (f"**{total_changed} chapter(s) with prose changes; "
            f"{len(only_work)} new chapter(s).**")
    out.insert(4, head)
    out.insert(5, "")
    return "\n".join(out) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--export", default=EXPORT_DEFAULT)
    ap.add_argument("--books", nargs="+",
                    default=sorted(glob.glob("source/book*.txt")))
    ap.add_argument("--context", type=int, default=140,
                    help="max chars shown per paragraph (default 140)")
    ap.add_argument("--out", default="-")
    args = ap.parse_args(argv)

    exp, parts = export_chapters(args.export)
    wrk = work_chapters(args.books, parts)
    if not exp or not wrk:
        ap.error("could not parse export and/or working chapters")
    text = render(exp, wrk, args.context)
    if args.out == "-":
        sys.stdout.write(text)
    else:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"wrote {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
