#!/usr/bin/env python3
"""Distinctive-word echo detector.

Readers barely notice a repeated 'the' but snag hard on a vivid word
reused a paragraph later ('luminous ... luminous'). This flags *uncommon*
content words (length >= 7, with a low-ish whole-book count so names and
ordinary words drop out) that recur within a short token window.

Different from the phrase scanner: that finds repeated *constructions*;
this finds a single striking word echoing itself locally.

Zero third-party dependencies. Python 3.8+.
"""
from __future__ import annotations

import argparse
import glob
import sys
from collections import Counter

from textlib import STOPWORDS, load_chapters, load_names


def find_echoes(chapters, window, min_len, max_count, names):
    corpus = Counter()
    for ch in chapters:
        corpus.update(ch.tokens)

    def candidate(w):
        return (len(w) >= min_len and w.isalpha() and w not in STOPWORDS
                and w not in names and 2 <= corpus[w] <= max_count)

    echoes = []  # (rarity, gap, chapter_label, word, ctx1, ctx2)
    for ch in chapters:
        toks = ch.tokens
        last = {}  # word -> position
        for i, w in enumerate(toks):
            if not candidate(w):
                continue
            if w in last and i - last[w] <= window:
                j = last[w]
                ctx1 = " ".join(toks[max(0, j - 5): j + 4])
                ctx2 = " ".join(toks[max(0, i - 5): i + 4])
                echoes.append((corpus[w], i - j, ch.label, w, ctx1, ctx2))
            last[w] = i
    # rarest first, then closest together
    echoes.sort(key=lambda e: (e[0], e[1]))
    return echoes


def render(echoes, top):
    out = ["# Distinctive-word echoes (auto-generated)", ""]
    out.append("Uncommon words reused within a short span — the repeats a "
               "reader actually notices. Rarest/closest first. "
               "Generated by `tools/echo_check.py`.")
    out.append("")
    if not echoes:
        out.append("- (none above thresholds)")
        return "\n".join(out) + "\n"
    for count, gap, label, word, ctx1, ctx2 in echoes[:top]:
        out.append(f"- **{word}** ({count}x book-wide, {gap} tokens apart) "
                   f"— {label}")
        out.append(f"    - …{ctx1}…")
        out.append(f"    - …{ctx2}…")
    out.append("")
    return "\n".join(out) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--books", nargs="+",
                    default=sorted(glob.glob("source/book*.txt")))
    ap.add_argument("--characters", default="characters.md")
    ap.add_argument("--window", type=int, default=45,
                    help="max token gap to count as an echo (default 45)")
    ap.add_argument("--min-len", type=int, default=7,
                    help="minimum word length to consider (default 7)")
    ap.add_argument("--max-count", type=int, default=120,
                    help="ignore words more frequent than this book-wide (default 120)")
    ap.add_argument("--top", type=int, default=80)
    ap.add_argument("--out", default="-")
    args = ap.parse_args(argv)
    if not args.books:
        ap.error("no book files found; pass --books")

    chapters = load_chapters(args.books)
    first, full = load_names(args.characters)
    echoes = find_echoes(chapters, args.window, args.min_len,
                         args.max_count, full)
    text = render(echoes, args.top)
    if args.out == "-":
        sys.stdout.write(text)
    else:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"wrote {args.out} ({len(echoes)} echoes)", file=sys.stderr)


if __name__ == "__main__":
    main()
