#!/usr/bin/env python3
"""Lint the manuscript against the hard rules in guidelines.md.

Turns the style guide from a passive doc into an active check: flags
banned words and banned constructions per chapter, with file:line
references you can click. The banned-word list is *parsed live* from
guidelines.md (the "Avoid these words and their variations" line), so
promoting a word there starts flagging it here the same day -- no second
list to maintain.

Advisory by design: every hit shows the matched text so a human makes the
call. Construction rules marked (heuristic) are deliberately loose and
will have false positives.

Zero third-party dependencies. Python 3.8+.
"""
from __future__ import annotations

import argparse
import glob
import os
import re
import sys
from collections import Counter

from textlib import iter_lines

# --- Banned constructions. (id, severity, compiled regex, note) ----------- #
# severity: "ban" = explicit guideline rule, "heuristic" = loose, review.
CONSTRUCTIONS = [
    ("indirect-self", "ban",
     re.compile(r"\b(found|let|made|caught|forced|told)\s+(?:him|her|my|them)self\b", re.I),
     "indirect phrasing ('found himself ...'); write the action directly"),
    ("neutral-expr", "ban",
     re.compile(r"\bneutral\b", re.I),
     "'neutral' to describe expression/demeanor"),
    ("vague-sound", "ban",
     re.compile(r"\b(?:a|an)?\s*(?:small|soft|little|quiet|low|odd|strange|"
                r"noncommittal|faint|muffled|involuntary)\s+(?:sound|noise)\b", re.I),
     "vague 'sound/noise'; use the proper verb (yelped, groaned) or cut"),
    ("arrived-with", "ban",
     re.compile(r"\b(?:summer|winter|spring|autumn|fall|morning|evening|night)\s+"
                r"arrived\s+with\b", re.I),
     "'<season> arrived with ...'; recast (e.g. 'summer was hot')"),
    ("absolute-clause", "heuristic",
     re.compile(r",\s+(?:its|his|her|their)\s+\w+\s+\w+(?:ed|ing|ic|al|ous|y)\b"),
     "possible descriptive clause after comma; prefer a plain noun phrase"),
]

# Words to skip when expanding banned bases (avoid obvious false positives).
INFLECT_TAIL = r"[a-z]{0,4}"


def load_banned_words(path):
    """Parse the 'Avoid these words and their variations' line of guidelines.md."""
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            if "avoid these words and their variations" in line.lower():
                after = line.split(":", 1)[1] if ":" in line else ""
                return [w.strip().lower() for w in after.split(",") if w.strip()]
    return []


def banned_patterns(words):
    """Compile a loose stem+suffix matcher for each banned base word."""
    pats = []
    for w in words:
        stem = w[:-1] if w.endswith("e") and len(w) > 3 else w
        pats.append((w, re.compile(r"\b" + re.escape(stem) + INFLECT_TAIL + r"\b", re.I)))
    return pats


def lint(paths, guidelines):
    words = load_banned_words(guidelines)
    wpats = banned_patterns(words)
    hits = []  # (book, chap, scene, lineno, rule, severity, match, text)
    for ln in iter_lines(paths):
        # Banned words.
        for base, pat in wpats:
            for m in pat.finditer(ln.text):
                hits.append((ln, f"word:{base}", "ban", m.group(0)))
        # Constructions.
        for rid, sev, pat, _note in CONSTRUCTIONS:
            m = pat.search(ln.text)
            if m:
                hits.append((ln, rid, sev, m.group(0).strip()))
        # Scene-opening "Arrived/Brought".
        first = re.match(r"^[\"']?(\w+)", ln.text)
        if ln.scene and first and first.group(1).lower() in {"arrived", "brought"}:
            # Only the first narrative line of a scene is the opener; cheap proxy:
            # flag any line that *starts* with these verbs.
            hits.append((ln, "scene-open-verb", "heuristic", first.group(1)))
    return words, hits


def render(words, hits, top):
    by_chap = {}
    for ln, rule, sev, match in hits:
        by_chap.setdefault((ln.book, ln.chapter), []).append((ln, rule, sev, match))

    out = ["# Guideline lint report (auto-generated)", ""]
    out.append(f"Banned words parsed from guidelines.md: {len(words)} "
               f"({', '.join(words)}).")
    out.append(f"Construction rules: {len(CONSTRUCTIONS)}. "
               f"Total hits: {len(hits)}.")
    out.append("")
    out.append("`(heuristic)` rules are loose — expect false positives. "
               "Generated by `tools/lint_guidelines.py`.")
    out.append("")

    tally = Counter(rule for _ln, rule, _s, _m in hits)
    out.append("## Hits by rule")
    out.append("")
    for rule, n in tally.most_common():
        out.append(f"- {rule} — {n}")
    out.append("")

    out.append("## Hits by chapter")
    out.append("")
    for key in sorted(by_chap):
        rows = by_chap[key]
        out.append(f"### {key[0]} ch{key[1]:02d} — {len(rows)} hits")
        for ln, rule, sev, match in rows[:top]:
            flag = " (heuristic)" if sev == "heuristic" else ""
            snippet = ln.text if len(ln.text) <= 100 else ln.text[:97] + "…"
            out.append(f"- L{ln.lineno} [{rule}{flag}] “{match}” — {snippet}")
        if len(rows) > top:
            out.append(f"- … {len(rows) - top} more")
        out.append("")
    return "\n".join(out) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--books", nargs="+",
                    default=sorted(glob.glob("source/book*.txt")))
    ap.add_argument("--guidelines", default="guidelines/guidelines.md")
    ap.add_argument("--top", type=int, default=60,
                    help="max hits listed per chapter (default 60)")
    ap.add_argument("--out", default="-")
    args = ap.parse_args(argv)
    if not args.books:
        ap.error("no book files found; pass --books")

    words, hits = lint(args.books, args.guidelines)
    text = render(words, hits, args.top)
    if args.out == "-":
        sys.stdout.write(text)
    else:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"wrote {args.out} ({len(hits)} hits)", file=sys.stderr)


if __name__ == "__main__":
    main()
