#!/usr/bin/env python3
"""Per-chapter style metrics, to catch *drift* rather than single sins.

The value is the time-series: a chapter sliding toward filter-heavy,
adverb-heavy, or metronomic prose shows up as a number before it becomes a
habit. Outliers (>1 std dev above the book mean) are flagged with ``!``.

Metrics per chapter:
  words, sents        - size
  len.avg, len.sd     - sentence length mean and std dev; low SD = monotone
  filter/1k           - distancing verbs (felt, saw, noticed, realized, ...)
  -ly/1k              - adverbs ending in -ly
  body/1k             - body-part nouns (the 'specify body parts' tic)
  dlg%                - share of sentences containing dialogue

Zero third-party dependencies. Python 3.8+.
"""
from __future__ import annotations

import argparse
import glob
import statistics
import sys

from textlib import WORD_RE, load_chapters, split_sentences

FILTER_VERBS = {
    "felt", "feel", "feels", "feeling", "saw", "see", "sees", "seeing",
    "heard", "hear", "hears", "watched", "watch", "watches", "watching",
    "noticed", "notice", "notices", "realized", "realised", "realize",
    "realise", "seemed", "seem", "seems", "wondered", "wonder", "wonders",
    "thought", "knew", "sensed", "observed", "decided",
}
BODY_PARTS = {
    "eyes", "eye", "face", "hand", "hands", "head", "chest", "jaw", "jaws",
    "shoulder", "shoulders", "throat", "lips", "lip", "fingers", "finger",
    "arm", "arms", "mouth", "neck", "brow", "chin", "cheek", "cheeks",
    "stomach", "gaze", "knee", "knees", "foot", "feet", "back",
}
LY_SKIP = {
    "only", "family", "reply", "apply", "supply", "ally", "rely", "holy",
    "italy", "july", "ugly", "early", "fully", "really",
}


def metric_row(ch):
    sents = split_sentences(ch.text)
    lengths = [len(WORD_RE.findall(s)) for s in sents] or [0]
    toks = ch.tokens
    n = len(toks) or 1
    filt = sum(1 for t in toks if t in FILTER_VERBS)
    body = sum(1 for t in toks if t in BODY_PARTS)
    ly = sum(1 for t in toks
             if t.endswith("ly") and len(t) >= 4 and t not in LY_SKIP)
    dlg = sum(1 for s in sents if '"' in s)
    return {
        "label": ch.label,
        "words": len(toks),
        "sents": len(sents),
        "len.avg": statistics.mean(lengths),
        "len.sd": statistics.pstdev(lengths) if len(lengths) > 1 else 0.0,
        "filter/1k": 1000 * filt / n,
        "-ly/1k": 1000 * ly / n,
        "body/1k": 1000 * body / n,
        "dlg%": 100 * dlg / (len(sents) or 1),
    }


# Metrics where a HIGH value is the concern (flag > mean+sd); len.sd is the
# inverse (LOW is the concern: monotone), handled separately.
HIGH_BAD = ["filter/1k", "-ly/1k", "body/1k"]
NUM_COLS = ["words", "sents", "len.avg", "len.sd",
            "filter/1k", "-ly/1k", "body/1k", "dlg%"]


def render(rows):
    means = {c: statistics.mean([r[c] for r in rows]) for c in NUM_COLS}
    sds = {c: (statistics.pstdev([r[c] for r in rows]) if len(rows) > 1 else 0.0)
           for c in NUM_COLS}

    out = ["# Style metrics (auto-generated)", ""]
    out.append("Per-chapter drift tracker. `!` marks an outlier "
               "(>1 SD worse than the book mean): high filter/adverb/body "
               "rates, or unusually *low* sentence-length SD (monotone). "
               "Generated by `tools/style_metrics.py`.")
    out.append("")
    header = ["chapter"] + NUM_COLS
    out.append("| " + " | ".join(header) + " |")
    out.append("|" + "|".join(["---"] * len(header)) + "|")

    def fmt(c, v):
        s = f"{v:.1f}" if isinstance(v, float) else str(v)
        bad = (c in HIGH_BAD and v > means[c] + sds[c]) or \
              (c == "len.sd" and v < means[c] - sds[c])
        return s + ("!" if bad else "")

    for r in rows:
        cells = [r["label"]] + [fmt(c, r[c]) for c in NUM_COLS]
        out.append("| " + " | ".join(cells) + " |")
    out.append("| **book mean** | "
               + " | ".join(f"{means[c]:.1f}" for c in NUM_COLS) + " |")
    out.append("")
    return "\n".join(out) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--books", nargs="+",
                    default=sorted(glob.glob("source/book*.txt")))
    ap.add_argument("--out", default="-")
    args = ap.parse_args(argv)
    if not args.books:
        ap.error("no book files found; pass --books")

    rows = [metric_row(ch) for ch in load_chapters(args.books)]
    if not rows:
        ap.error("no chapters parsed")
    text = render(rows)
    if args.out == "-":
        sys.stdout.write(text)
    else:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"wrote {args.out} ({len(rows)} chapters)", file=sys.stderr)


if __name__ == "__main__":
    main()
